//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC_User.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleMesseage", Namespace="http://localhost:55261/")]
    [System.SerializableAttribute()]
    public partial class SingleMesseage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesseageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgTypeField, value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgTo {
            get {
                return this.MsgToField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgToField, value) != true)) {
                    this.MsgToField = value;
                    this.RaisePropertyChanged("MsgTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Messeage {
            get {
                return this.MesseageField;
            }
            set {
                if ((object.ReferenceEquals(this.MesseageField, value) != true)) {
                    this.MesseageField = value;
                    this.RaisePropertyChanged("Messeage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:55261/", ConfigurationName="ServiceReference1.SendMesseageSoap")]
    public interface SendMesseageSoap {
        
        // CODEGEN: Generating message contract since element name messeages from namespace http://localhost:55261/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:55261/SendMultiple", ReplyAction="*")]
        MC_User.ServiceReference1.SendMultipleResponse SendMultiple(MC_User.ServiceReference1.SendMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:55261/SendMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_User.ServiceReference1.SendMultipleResponse> SendMultipleAsync(MC_User.ServiceReference1.SendMultipleRequest request);
        
        // CODEGEN: Generating message contract since element name messeage from namespace http://localhost:55261/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:55261/SendSingle", ReplyAction="*")]
        MC_User.ServiceReference1.SendSingleResponse SendSingle(MC_User.ServiceReference1.SendSingleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:55261/SendSingle", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_User.ServiceReference1.SendSingleResponse> SendSingleAsync(MC_User.ServiceReference1.SendSingleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMultiple", Namespace="http://localhost:55261/", Order=0)]
        public MC_User.ServiceReference1.SendMultipleRequestBody Body;
        
        public SendMultipleRequest() {
        }
        
        public SendMultipleRequest(MC_User.ServiceReference1.SendMultipleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:55261/")]
    public partial class SendMultipleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_User.ServiceReference1.SingleMesseage[] messeages;
        
        public SendMultipleRequestBody() {
        }
        
        public SendMultipleRequestBody(MC_User.ServiceReference1.SingleMesseage[] messeages) {
            this.messeages = messeages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMultipleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMultipleResponse", Namespace="http://localhost:55261/", Order=0)]
        public MC_User.ServiceReference1.SendMultipleResponseBody Body;
        
        public SendMultipleResponse() {
        }
        
        public SendMultipleResponse(MC_User.ServiceReference1.SendMultipleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:55261/")]
    public partial class SendMultipleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMultipleResult;
        
        public SendMultipleResponseBody() {
        }
        
        public SendMultipleResponseBody(string SendMultipleResult) {
            this.SendMultipleResult = SendMultipleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSingleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSingle", Namespace="http://localhost:55261/", Order=0)]
        public MC_User.ServiceReference1.SendSingleRequestBody Body;
        
        public SendSingleRequest() {
        }
        
        public SendSingleRequest(MC_User.ServiceReference1.SendSingleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:55261/")]
    public partial class SendSingleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_User.ServiceReference1.SingleMesseage messeage;
        
        public SendSingleRequestBody() {
        }
        
        public SendSingleRequestBody(MC_User.ServiceReference1.SingleMesseage messeage) {
            this.messeage = messeage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSingleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSingleResponse", Namespace="http://localhost:55261/", Order=0)]
        public MC_User.ServiceReference1.SendSingleResponseBody Body;
        
        public SendSingleResponse() {
        }
        
        public SendSingleResponse(MC_User.ServiceReference1.SendSingleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:55261/")]
    public partial class SendSingleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSingleResult;
        
        public SendSingleResponseBody() {
        }
        
        public SendSingleResponseBody(string SendSingleResult) {
            this.SendSingleResult = SendSingleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMesseageSoapChannel : MC_User.ServiceReference1.SendMesseageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMesseageSoapClient : System.ServiceModel.ClientBase<MC_User.ServiceReference1.SendMesseageSoap>, MC_User.ServiceReference1.SendMesseageSoap {
        
        public SendMesseageSoapClient() {
        }
        
        public SendMesseageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMesseageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMesseageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMesseageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_User.ServiceReference1.SendMultipleResponse MC_User.ServiceReference1.SendMesseageSoap.SendMultiple(MC_User.ServiceReference1.SendMultipleRequest request) {
            return base.Channel.SendMultiple(request);
        }
        
        public string SendMultiple(MC_User.ServiceReference1.SingleMesseage[] messeages) {
            MC_User.ServiceReference1.SendMultipleRequest inValue = new MC_User.ServiceReference1.SendMultipleRequest();
            inValue.Body = new MC_User.ServiceReference1.SendMultipleRequestBody();
            inValue.Body.messeages = messeages;
            MC_User.ServiceReference1.SendMultipleResponse retVal = ((MC_User.ServiceReference1.SendMesseageSoap)(this)).SendMultiple(inValue);
            return retVal.Body.SendMultipleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_User.ServiceReference1.SendMultipleResponse> MC_User.ServiceReference1.SendMesseageSoap.SendMultipleAsync(MC_User.ServiceReference1.SendMultipleRequest request) {
            return base.Channel.SendMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_User.ServiceReference1.SendMultipleResponse> SendMultipleAsync(MC_User.ServiceReference1.SingleMesseage[] messeages) {
            MC_User.ServiceReference1.SendMultipleRequest inValue = new MC_User.ServiceReference1.SendMultipleRequest();
            inValue.Body = new MC_User.ServiceReference1.SendMultipleRequestBody();
            inValue.Body.messeages = messeages;
            return ((MC_User.ServiceReference1.SendMesseageSoap)(this)).SendMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_User.ServiceReference1.SendSingleResponse MC_User.ServiceReference1.SendMesseageSoap.SendSingle(MC_User.ServiceReference1.SendSingleRequest request) {
            return base.Channel.SendSingle(request);
        }
        
        public string SendSingle(MC_User.ServiceReference1.SingleMesseage messeage) {
            MC_User.ServiceReference1.SendSingleRequest inValue = new MC_User.ServiceReference1.SendSingleRequest();
            inValue.Body = new MC_User.ServiceReference1.SendSingleRequestBody();
            inValue.Body.messeage = messeage;
            MC_User.ServiceReference1.SendSingleResponse retVal = ((MC_User.ServiceReference1.SendMesseageSoap)(this)).SendSingle(inValue);
            return retVal.Body.SendSingleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_User.ServiceReference1.SendSingleResponse> MC_User.ServiceReference1.SendMesseageSoap.SendSingleAsync(MC_User.ServiceReference1.SendSingleRequest request) {
            return base.Channel.SendSingleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_User.ServiceReference1.SendSingleResponse> SendSingleAsync(MC_User.ServiceReference1.SingleMesseage messeage) {
            MC_User.ServiceReference1.SendSingleRequest inValue = new MC_User.ServiceReference1.SendSingleRequest();
            inValue.Body = new MC_User.ServiceReference1.SendSingleRequestBody();
            inValue.Body.messeage = messeage;
            return ((MC_User.ServiceReference1.SendMesseageSoap)(this)).SendSingleAsync(inValue);
        }
    }
}
